spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/study
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibername:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibername.SQL: debug
    org.hibernate.type: trace
